# Generated by Django 4.1.3 on 2024-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shoes", "Shoes"),
                            ("jeans", "Jeans"),
                            ("tshirts", "T-shirts"),
                            ("sweatpants", "Sweatpants"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("image", models.ImageField(upload_to="products/images")),
            ],
        ),
    ]
