# Generated by Django 4.1.3 on 2024-11-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("motor", "0005_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="motor.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="items",
            field=models.ManyToManyField(related_name="carts", to="motor.cartitem"),
        ),
    ]
